export const categories = [
  { value: "Clothing", label: "Clothing & Apparel" },
  { value: "Electronics", label: "Electronics & Gadgets" },
  { value: "Footwear", label: "Footwear & Shoes" },
  { value: "Bags", label: "Bags & Luggage" },
  { value: "Jewelry", label: "Jewelry & Accessories" },
  { value: "Beauty", label: "Beauty & Personal Care" },
  { value: "Health", label: "Health & Wellness" },
  { value: "Home", label: "Home & Kitchen" },
  { value: "Furniture", label: "Furniture & Decor" },
  { value: "Toys", label: "Toys & Games" },
  { value: "Sports", label: "Sports & Outdoors" },
  { value: "Automotive", label: "Automotive & Tools" },
  { value: "Books", label: "Books & Stationery" },
  { value: "Music", label: "Music & Instruments" },
  { value: "Movies", label: "Movies & Entertainment" },
  { value: "Food", label: "Food & Groceries" },
  { value: "Baby", label: "Baby & Kids" },
  { value: "Pets", label: "Pet Supplies" },
  { value: "Office", label: "Office & School Supplies" },
  { value: "Software", label: "Software & Digital Products" },
];