export const shopCategories = [
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "footwear", label: "Footwear" },
  { value: "accessories", label: "Fashion Accessories" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "electronics", label: "Electronics" },
  { value: "mobiles", label: "Mobile Phones & Accessories" },
  { value: "computers", label: "Computers & Laptops" },
  { value: "gaming", label: "Gaming & Consoles" },
  { value: "home", label: "Home & Living" },
  { value: "furniture", label: "Furniture" },
  { value: "kitchen", label: "Kitchen & Dining" },
  { value: "appliances", label: "Home Appliances" },
  { value: "hardware", label: "Hardware & Tools" },
  { value: "automotive", label: "Automotive & Motorcycle" },
  { value: "grocery", label: "Grocery & Everyday Essentials" },
  { value: "beverages", label: "Beverages" },
  { value: "baby", label: "Baby Products" },
  { value: "toys", label: "Toys & Games" },
  { value: "sports", label: "Sports & Outdoor" },
  { value: "fitness", label: "Fitness Equipment" },
  { value: "health", label: "Health & Wellness" },
  { value: "books", label: "Books & Stationery" },
  { value: "pets", label: "Pet Supplies" },
  { value: "music", label: "Musical Instruments" },
  { value: "crafts", label: "Arts & Crafts" },
  { value: "garden", label: "Garden & Outdoor Living" },
  { value: "pharmacy", label: "Pharmacy & Healthcare" },
  { value: "office", label: "Office Supplies" },
  { value: "party", label: "Party Supplies" }
];
